name: lapisco_challenge
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  carousel_slider: ^5.0.0
  fl_chart: ^0.70.2
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  geocoding: ^3.0.0
  geolocator: ^13.0.2
  get_ip_address: ^0.0.7
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/weather_icons/
