Map<int, Map<String, String>> weatherCodeAsset = {
  0: {'name': 'Clear', 'asset': 'clear@4x.png'},
  1: {'name': 'Mostly Clear', 'asset': 'mostly-clear@4x.png'},
  2: {'name': 'Partly Cloudy', 'asset': 'partly-cloudy@4x.png'},
  3: {'name': 'Overcast', 'asset': 'overcast@4x.png'},
  45: {'name': 'Fog', 'asset': 'fog@4x.png'},
  48: {'name': 'Icy Fog', 'asset': 'rime-fog@4x.png'},
  51: {'name': 'Light Drizzle', 'asset': 'light-drizzle@4x.png'},
  53: {'name': 'Drizzle', 'asset': 'moderate-drizzle@4x.png'},
  55: {'name': 'Heavy Drizzle', 'asset': 'dense-drizzle@4x.png'},
  80: {'name': 'Light Showers', 'asset': 'light-rain@4x.png'},
  81: {'name': 'Showers', 'asset': 'moderate-rain@4x.png'},
  82: {'name': 'Heavy Showers', 'asset': 'heavy-rain@4x.png'},
  61: {'name': 'Light Rain', 'asset': 'light-rain@4x.png'},
  63: {'name': 'Rain', 'asset': 'moderate-rain@4x.png'},
  65: {'name': 'Heavy Rain', 'asset': 'heavy-rain@4x.png'},
  56: {'name': 'Light Freezing Drizzle', 'asset': 'light-freezing-drizzle@4x.png'},
  57: {'name': 'Freezing Drizzle', 'asset': 'dense-freezing-drizzle@4x.png'},
  66: {'name': 'Light Freezing Rain', 'asset': 'light-freezing-rain@4x.png'},
  67: {'name': 'Freezing Rain', 'asset': 'heavy-freezing-rain@4x.png'},
  71: {'name': 'Light Snow', 'asset': 'slight-snowfall@4x.png'},
  73: {'name': 'Snow', 'asset': 'moderate-snowfall@4x.png'},
  75: {'name': 'Heavy Snow', 'asset': 'heavy-snowfall@4x.png'},
  77: {'name': 'Snow Grains', 'asset': 'snowflake@4x.png'},
  85: {'name': 'Light Snow Showers', 'asset': 'slight-snowfall@4x.png'},
  86: {'name': 'Snow Showers', 'asset': 'heavy-snowfall@4x.png'},
  95: {'name': 'Thunderstorm', 'asset': 'thunderstorm@4x.png'},
  96: {'name': 'Light T-storm w/ Hail', 'asset': 'thunderstorm-with-hail@4x.png'},
  99: {'name': 'T-storm w/ Hail', 'asset': 'thunderstorm-with-hail@4x.png'},
};